# Generated by Django 4.1.1 on 2022-09-16 08:54

from django.db import migrations, models
import showtime.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_start_time', models.DateTimeField(validators=[showtime.models.validate_time])),
                ('show_end_time', models.DateTimeField(validators=[showtime.models.validate_time])),
                ('date_created', models.DateField(auto_now_add=True)),
                ('show_type', models.CharField(choices=[('MORNING SHOW', 'MORNING SHOW'), ('AFTERNOON SHOW', 'AFTERNOON SHOW'), ('EVENING SHOW', 'EVENING SHOW'), ('NIGHT SHOW', 'NIGHT SHOW')], max_length=150)),
            ],
        ),
    ]
