# Generated by Django 4.1.1 on 2022-09-16 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
        ('Studio', '0001_initial'),
        ('showtime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('still_playing', models.BooleanField(default=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='movie', to='movie.movie')),
                ('show_time', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='show_time', to='showtime.showtime')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='studio', to='Studio.studio')),
            ],
        ),
    ]
