# Generated by Django 4.1.1 on 2022-09-21 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showtime', '0002_shows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='show_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shows', to='showtime.showtime'),
        ),
    ]
