# Generated by Django 4.1.1 on 2022-09-16 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('studio_details', models.TextField()),
                ('studio_type', models.CharField(choices=[('MULTIPLEX', 'MULTIPLEX'), ('3D', '3D'), ('2D', '2D')], max_length=100)),
                ('still_playing', models.BooleanField(default=True)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
