# Generated by Django 4.1.1 on 2022-09-20 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userprofiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='user_image')),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.IntegerField(validators=[userprofiles.models.age_validator])),
                ('address', models.CharField(max_length=350)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], max_length=20)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
