# Generated by Django 4.1.1 on 2022-09-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
