# Generated by Django 4.1.1 on 2022-09-20 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_bookings_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='seats',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
