# Generated by Django 4.1.1 on 2022-09-20 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showtime', '0002_shows'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='shows',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows_purchased', to='showtime.shows'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
